// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/knwoop/swagger-sample/handler"
)

// Injectors from injector.go:

func InitializeApp() *handler.Handler {
	helloHandler := handler.NewHelloHandler()
	handlerHandler := &handler.Handler{
		Hello: helloHandler,
	}
	return handlerHandler
}
