// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/knwoop/swagger-sample/handler"
)

// Injectors from injector.go:

func InitializeApp() *handler.AppHandler {
	helloHandler := handler.NewHelloHandler()
	appHandler := handler.NewAppHandler(helloHandler)
	return appHandler
}
